const icons = {
    'error': ['far', 'question'],
    'new-chat': ['far', 'pen-to-square'],
    'home': ['fas', 'house'],
    // 'home-far': ['far', 'house'],
    // 'user': ['far', 'user'],
    'user': ['fas', 'user'],
    'chat': ['fas', 'comment'],
    'letter': ['far', 'envelope'],
    'blind': ['fas', 'rotate-right'],
    'search': ['fas', 'magnifying-glass'],
    'close': ['fas', 'xmark'],
    'back': ['fas', 'chevron-left'],
    'clear-circle': ['fas', 'circle-xmark'],
    'menu': ['fas', 'bars'],
    'image': ['far', 'image'],
    'send': ['fas', 'circle-arrow-up'],
    'error-send': ['fas', 'circle-exclamation'],
    'more': ['fas', 'ellipsis'],
    'bookmark': ['far', 'star'],
    'bookmarked': ['fas', 'star'],
    'bell': ['far', 'bell'],
    'bell-slash': ['far', 'bell-slash'],
    'flag': ['far', 'flag'],
    'ban': ['fas', 'ban'],
    'leave': ['fas', 'right-from-bracket'],
    'setting': ['fas', 'gear'],
    'tool': ['fas', 'screwdriver-wrench'],
    'add-user': ['fas', 'user-plus'],
    'camera': ['fas', 'camera'],
    'hand-shake': ['far', 'handshake'],
    'reply': ['fas', 'reply'],
    'plus': ['fas', 'plus'],
    'pencil': ['fas', 'pencil'],
    're': ['fas', 'rotate-right'],
    're-far': ['far', 'rotate-right'],
    'share': ['fas', 'share-nodes'],
  };
  
  export default icons;